name: Run npm tests

on:
  push:
    branches:
      - master # Change this to the default branch of your repository
      - develop
      - ci
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run npm tests
        run: npm test
